### ISSUE TITLE
Two databases

### ISSUE THREAD

**Issue by mkl-strnge** [AIHelpsSoft/documentations#1]
Hi! We have 2 departments, with separate databases 518822,151232. In the new version, I need to put in code - database: '518822' . But we need single button that will lead user to department selection. How I can do that? I tested like that - database: ['518822', '151232'] , but this doesn't work.

**Comment by Kolomiiyets** [comment]
I got this task quite recently, I think It will be ready to use in next week. I will let you know when it is finished. sorry for delay

**Comment by Kolomiiyets** [comment]
The problem didn't solve because you need to unite your databases, just get into the contact support team
