### ISSUE TITLE
Content is not scrolling on mobile device

### ISSUE THREAD

**Issue by mkl-strnge** [AIHelpsSoft/documentations#2]
Iphone 7, Safari
https://wizard-salon.com.ua/video_2019-11-22_10-34-03.mp4

**Comment by Kolomiiyets** [comment]
Can you reproduce this bug yet?

**Comment by Kolomiiyets** [comment]
@mkl-strnge Can you reproduce this bug yet?

**Comment by Kolomiiyets** [comment]
just close this issue because I don't get an answer
