### ISSUE TITLE
Caching and compression for js and css files

### ISSUE THREAD

**Issue by mkl-strnge** [AIHelpsSoft/documentations#3]
There are errors in the Google Lighthouse report, please enable apache or nginx modules.
![2019-12-15_065707](https://user-images.githubusercontent.com/48006264/70858319-a9f7a500-1f08-11ea-95a7-0e7ffaf0894c.jpg)
![2019-12-15_065647](https://user-images.githubusercontent.com/48006264/70858321-a9f7a500-1f08-11ea-8e9d-c90daf05a35a.jpg)

**Comment by Kolomiiyets** [comment]
right now all src files moved to amazon s3, so loading should be faster, also enable caching and compression
